#!/usr/bin/env bash

# Arguments:
#                                      isPrivate pkgDescr              isGlobal binNames     mainName   supportedOSnames keywords         licenseID
./.fixtures/create-package foo-lib-cli n        'foo-lib-cli package' n        'foo-cli'   'foo-lib'  '!win32'         'foo,bar,lib+cli' BSD-3-Clause
