#!/usr/bin/env bash

# Arguments:
#                                  isPrivate pkgDescr      isGlobal binNames mainName supportedOSnames keywords       licenseID
./.fixtures/create-package foo-cli n        'foo-cli pkg' y        ''       ''       'linux,darwin'   'foo,bar,cli'  MIT
