#!/usr/bin/env bash

# Arguments:
#                                  isPrivate pkgDescr          isGlobal binNames mainName supportedOSnames keywords       licenseID
./.fixtures/create-package foo-lib n        'foo-lib package' n        ''       ''       ''               'foo,bar,lib'  GPL-3.0
